[PLAT-7221]Return proper error message provided by YBA as terraform output
Summary:
Earlier only status code was returned if a YBA operation failed. This makes it hard to debug without logging into the YBA instance and parsing through the logs.
This change introduces a function that parses through the response if error is returned from the API, extracts the response message as printed in the YBA logs and displays the same on the console running terraform commands.
Sample outputs:

```
Error: Resource: Customer, Operation: Create - 400 Bad Request: Field: password, Error: This field is required

Error: Resource: Customer, Operation: Create - 400 Bad Request: Cannot register multiple accounts in Single tenancy.

Error: Resource: Customer, Operation: Create - 409 Conflict: Customer already registered.

Error: Resource: Storage Config, Operation: Create - 400 Bad Request: Field: name, Error: size must be between 1 and 50

Error: Resource: Backups, Operation: Create - 400 Bad Request: Cannot initiate backup with empty Keyspace postgres
```

LOG INFO will now also display the percentage of completion of task if TF_LOG argument is set during terraform commands

Sample:

```
yb_universe.aws_universe: Still creating... [10s elapsed]
2023-04-13T13:07:17.611Z [INFO]  provider.terraform-provider-yugabyte-platform: Task "Creating Universe : aws-yba-aws-dkumar" completion percentage: 9%: tf_provider_addr=provider tf_rpc=ApplyResourceChange @caller=/home/deeptikumar/code/terraform-provider-yugabytedb-anywhere/internal/utils/utils.go:126 tf_resource_type=yb_universe @module=provider tf_req_id=b0b424ff-7532-1556-2f52-9e430f54c05e timestamp=2023-04-13T13:07:17.610Z
2023-04-13T13:07:17.611Z [INFO]  provider.terraform-provider-yugabyte-platform: Substasks: Title: "Provisioning", Status: "Running"; Title: "Installing software", Status: "Created"; Title: "Updating gflags", Status: "Created"; Title: "Starting Master Process", Status: "Created"; Title: "Starting Node processes", Status: "Created"; Title: "Configuring the universe", Status: "Created"; : tf_provider_addr=provider tf_resource_type=yb_universe tf_req_id=b0b424ff-7532-1556-2f52-9e430f54c05e tf_rpc=ApplyResourceChange @caller=/home/deeptikumar/code/terraform-provider-yugabytedb-anywhere/internal/utils/utils.go:136 @module=provider timestamp=2023-04-13T13:07:17.610Z
2023-04-13T13:07:17.611Z [INFO]  provider.terraform-provider-yugabyte-platform: 2023/04/13 13:07:17 [TRACE] Waiting 10s before next try: timestamp=2023-04-13T13:07:17.610Z
```

Test Plan: Terraform workflow to ensure there are no breaking changes

Reviewers: sneelakantan

Reviewed By: sneelakantan

Subscribers: sb-yb

Differential Revision: https://phabricator.dev.yugabyte.com/D24387