[PLAT-8844] delete_backup field change causes "Error: time: missing unit in duration" to be thrown
Summary:
The fields allowed for updation in Backup Schedule resource are
frequency : Frequency of backups
delete_backups : Delete backups associated with schedule.
Frequency unit is not required for changes to delete_backups, but since state file stores the
frequency in milliseconds and not duration, the following error is thrown:

```
Error: time: missing unit in duration "3600000"
│
│   with yb_backups.aws_universe_backup_ysql,
│   on main.tf line 248, in resource "yb_backups" "aws_universe_backup_ysql":
│  248: resource "yb_backups" "aws_universe_backup_ysql" {
```
Solution is to frequency field has change, else don’t check for unit

Test Plan: Add check if frequency is changed in the configuration file

Reviewers: sneelakantan

Reviewed By: sneelakantan

Differential Revision: https://phorge.dev.yugabyte.com/D25336