[PLAT-8901]Bump up version restriction for backup schedules and restores
Summary:
RestoreBackupYbc checked for taskId == null [[[ https://github.com/yugabyte/yugabyte-db/blob/c6a1bcd4e1c03146de8d921d5cf6ef181c6e8608/managed/src/main/java/com/yugabyte/yw/commissioner/tasks/subtasks/RestoreBackupYbc.java#L123 | here ]]] in the Restore workflow before the bug fix. Since go-client does not have a concept of null strings (only null string pointers), the block of code isn’t accessed, throwing the following error in the workflow:

```
java.lang.RuntimeException: Task id  status: Task not found on YB-Controller
	at com.yugabyte.yw.commissioner.YbcTaskBase.handleTaskCompleteStage(YbcTaskBase.java:91)
	at com.yugabyte.yw.commissioner.YbcTaskBase.pollTaskProgress(YbcTaskBase.java:66)
	at com.yugabyte.yw.commissioner.tasks.subtasks.RestoreBackupYbc.run(RestoreBackupYbc.java:191)
	at com.yugabyte.yw.commissioner.TaskExecutor$AbstractRunnableTask.run(TaskExecutor.java:810)
	at com.yugabyte.yw.commissioner.TaskExecutor$RunnableSubTask.run(TaskExecutor.java:1204)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at com.yugabyte.yw.common.logging.MDCAwareRunnable.run(MDCAwareRunnable.java:46)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
YW 2023-05-13T18:24:30.439Z [DEBUG] d93cd81e-a52e-4cb7-b1f4-eeb56d0b5c8e from TaskExecutor in TaskPool-RestoreBackup(8fd29236-8848-4171-8a35-2ddcd70c6a58)-0 - Task creator callstack:
com.yugabyte.yw.commissioner.TaskExecutor$SubTaskGroup.addSubTask(TaskExecutor.java:538)
com.yugabyte.yw.commissioner.tasks.UniverseTaskBase.createRestoreBackupYbcTask(UniverseTaskBase.java:2510)
com.yugabyte.yw.commissioner.tasks.UniverseTaskBase.createAllRestoreSubtasks(UniverseTaskBase.java:2364)
com.yugabyte.yw.commissioner.tasks.RestoreBackup.run(RestoreBackup.java:69)
com.yugabyte.yw.commissioner.TaskExecutor$AbstractRunnableTask.run(TaskExecutor.java:810)
com.yugabyte.yw.commissioner.TaskExecutor$RunnableTask.run(TaskExecutor.java:1019)
java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
java.util.concurrent.FutureTask.run(FutureTask.java:266)
com.yugabyte.yw.common.logging.MDCAwareRunnable.run(MDCAwareRunnable.java:46)
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
java.lang.Thread.run(Thread.java:750)
```
The linked issue resolves this by checking for null or blank strings. Since this issue is faced in the recently released versions of YBA (2.17.3 and 2.18), restriction in Terraform has been placed to allow backups and restores on builds with the fix present (2.18.1.0-b20 and later).

Test Plan:
Test on versions above 2.18.1.0-b20 for backups
Block backups below specified version

Reviewers: sneelakantan

Reviewed By: sneelakantan

Differential Revision: https://phorge.dev.yugabyte.com/D25443